site_name: Asset Manager Browser
site_favicon: logo.svg
site_author: shuo.man@hpe.com
site_description: HPE Asset Manager online document
repo_url: https://hpln.hpe.com/contentoffering/am-browser
repo_name: Download

pages:
- Overview: index.md
- Getting Started:
    - Installation: start/installation.md
    - Upgrade and Migration: start/upgrade.md
    - Configuration: start/configuration.md
    - Troubleshooting: start/troubleshooting.md
    - Security: start/security.md
    - FAQ: start/faq.md
- Features:
    - Search: features/search.md
    - Insight: features/insight.md
    - Viewer: features/viewer.md
    - Builder:
      - View: features/builder/view.md
      - Template: features/builder/template.md
      - Graph: features/builder/graph.md
    - SAM: features/sam.md
    - My Assets: features/myassets.md
    - Adapter: features/adpater.md
- Sizing Guide: sizing/introduction.md
- Community:
    - Slack: slack.md
    - Blogs: blogs.md

theme_dir: 'material'
# theme_dir: 'flatly'
# theme: readthedocs
# theme: Bootstrap

# extra_css: ['hpe.css']
extra:
  version: '1.1'
  logo: 'logo.svg'
  palette:
    primary: 'Teal'
#   author: 
#     github: 'masogit'
#     twitter: 'manshuo'