site_name: Asset Manager Browser
site_favicon: favicon.ico
site_author: shuo.man@hpe.com

pages:
- Overview: index.md
- Getting Started: 
    - Installation: start/installation.md
    - Configuration: start/configuration.md
    - Troubleshooting: start/troubleshooting.md
    - FAQ: start/faq.md
- Features:
    - Search: features/search.md
    - Insight: features/insight.md
    - Viewer: features/viewer.md
    - Builder: features/builder.md
    - Graph: features/graph.md
    - Adapter: features/adpater.md
- Slack: slack.md
- Blogs: blogs.md

theme_dir: 'flatly'
# theme: readthedocs

extra_css: [hpe.css]
