site_name: AM Browser
site_favicon: favicon.ico
site_author: shuo.man@hpe.com

pages:
- Overview: index.md
- Installation: installation.md
- Features:
    - Search: features/search.md
    - Insight: features/insight.md
    - Viewer: features/viewer.md
    - Builder: features/builder.md
    - Graph: features/graph.md
    - Adapter: features/adpater.md
- Troubleshooting: troubleshooting.md

# theme: flatly

# extra_css: [hpe.css]
